services:
    eliza:
        command: ["yarn", "start", "--character=./characters/eliza.character.json"]
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - ./data:/app/data
        environment:
            - TWITTER_PASSWORD=
            - TWITTER_USERNAME=
            - TWITTER_EMAIL=
            - TWITTER_DRY_RUN=false
            - OPENROUTER_API_KEY=
            - POST_INTERVAL_MIN=60
            - POST_INTERVAL_MAX=120
            - TWITTER_POLL_INTERVAL=90
            - ENABLE_ACTION_PROCESSING=false
            - MAX_ACTIONS_PROCESSING=
            - DISCORD_API_TOKEN=
            - DISCORD_APPLICATION_ID=
            - TOGETHER_API_KEY=
            - TAVILY_API_KEY=
            - DAEMON_PROCESS=false
            - SERVER_PORT=3000
        ports:
            - "3000:3000"
        restart: always
